default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: <%= ENV['LIGHTING_SEO_DEV_DATABASE_PASSWORD'] %>
  host: localhost
  port: 5432

development:
  <<: *default
  database: lightning_seo_dev_development

test:
  <<: *default
  database: lightning_seo_dev_test

production:
  <<: *default
  database: lightning_seo_dev_production
  url: <%= ENV['DATABASE_URL'] %>